version: "3"
services:
  smtp_to_telegram:
    build: .
    container_name: smtp_to_tg
    environment:
      ST_TELEGRAM_BOT_TOKEN: 1111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      ST_TELEGRAM_CHAT_IDS: |-
        mail1a@some_recipient>CHAT_ID1,
        mail2@some_sender<CHAT_ID2
    ports:
      - "25:2525"  # SMTP
    restart: unless-stopped
